# Generated by Django 2.2.3 on 2019-07-30 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0004_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='response_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
