# Generated by Django 2.2.3 on 2019-07-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0005_auto_20190730_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='response_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
