# Generated by Django 2.2.3 on 2019-07-30 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0007_auto_20190730_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='response_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
