# Generated by Django 2.2.3 on 2019-07-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0008_auto_20190730_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
