# Generated by Django 2.2.3 on 2019-08-02 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0011_auto_20190801_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
